### ISSUE TITLE
smokedetector not found (version 1.0.2)

### ISSUE THREAD

**Issue by rwaaren** [rvdvoorde/domoticz-homewizard#1]
Smokedetector was not found until I changed two lines in plugin.py from

  if ( hw_types[str(sens_id)] == "smoke" ):
                elif ( sens_type == "smoke" ):

to

  if ( hw_types[str(sens_id)] == "smoke868" ):
                elif ( sens_type == "smoke868" ):

**Comment by rvdvoorde** [comment]
Since smoke is also used as a device I added smoke and smoke868.

Thanks for you comment!
