### ISSUE TITLE
Somfy "MY" preset not available

### ISSUE THREAD

**Issue by MuadDib007** [rvdvoorde/domoticz-homewizard#12]
I have Somfy blinds connected to Domoticz via Homewizard.
It seems the command implemented as "STOP" is also used as "Preset".

So when the blinds are not moving and I press "STOP" they will move to my preset position.
When the blinds are moving and I press "STOP" they will stop moving.

It would be great to have the option "Preset" in Domoticz, so you know the blinds are set to that position.
Now, when pressing "STOP" Domoticz thinks they are open, which is not exactly true.

**Comment by rvdvoorde** [comment]
This plugin can only use the commands available by the homewizard. If the homewizard doesn;t support it then this plugin cannot support it.
