### ISSUE TITLE
Energylink values

### ISSUE THREAD

**Issue by 0xi3** [rvdvoorde/domoticz-homewizard#18]
My homewizard energylink is reading, but only got strange values in the overview.
![hw - electricity](https://user-images.githubusercontent.com/39808756/40802065-da31ddd0-6514-11e8-8305-02459f097746.PNG)
And when in settings I have no idea if my value settings are correct:
![energylink settings](https://user-images.githubusercontent.com/39808756/40802090-eccba91c-6514-11e8-8ae4-bacd7067b88b.PNG)

Can anyone advise me for which settings I need to choose?

**Comment by ghost** [comment]
I think I've got exactly the same issue. The picture "456" shows the correct value, but when I open the log it only shows me the value 0 (zero). I havent got a complete setup yet, I just started with Domoticz.

**Comment by azsystem** [comment]
The settings as described above, are working for me... only the daily total is not very accurate. It is within a 2kwh range.
