### ISSUE TITLE
Wattcher energy usage statistics one day off

### ISSUE THREAD

**Issue by kalonly** [rvdvoorde/domoticz-homewizard#19]
![screenshot 2018-06-02 at 05 12 23](https://user-images.githubusercontent.com/39847327/40869900-e37d0d14-6623-11e8-959c-343e5b082391.png)
Great plugin!

One small issue with the Wattcher daily totals: the daily total is one day off: today is saturday, but the daily total energy usage for today is already filled in with the usage totals of yesterday (friday). 

Hope my attachment makes it clear.

**Comment by rvdvoorde** [comment]
I believe this is not related to the homewizard plugin since the plugin just sends the data received from the homewizard to domoticz.
