### ISSUE TITLE
Smartwares SH8-90901

### ISSUE THREAD

**Issue by c4coer** [rvdvoorde/domoticz-homewizard#21]
I installed the new plugs:

Smartwares SH8-90901

but they are not detected by the plug-in.

thank you

**Comment by ijzen006** [comment]
please provide your get-sensors and get-status information regarding the switches so we can figure out how to process them.
Should be http://ip-address:port/password/get-status like http://10.0.0.2:80/1234/get-status and get_sensors

**Comment by c4coer** [comment]
Hello
the problem is precisely it does not appear in the web interface.

we can order this take only the application of android or ios.

I have to contact Hw support, for that

**Comment by c4coer** [comment]
get statut for socket:
{"id":26,"type":"proswitch","status":"on"}]

**Comment by c4coer** [comment]
here I add it in the list of switches,   voila je l'ai rajouter, cela fonctionne sans probleme 
[plugin.zip](https://github.com/rvdvoorde/domoticz-homewizard/files/2343304/plugin.zip)

**Comment by rvdvoorde** [comment]
Thanks c4coer, added it to the current version
