### ISSUE TITLE
Domoticz slow reacting 

### ISSUE THREAD

**Issue by Th3Cub3** [rvdvoorde/domoticz-homewizard#22]
Ls,

i had the plugin active but Domoticz is now really slow, and when i go to hardware i dont see the homewizard plug not active anymore.  
the domoticz Log file is now also empty ?, and i can do anything becours of the slow uses or it looks like it crashes fast ? every few seconds

the: http://192.168.2.28/CCCCCCC/swlist
status | "failed"
-- | --
error | 1
version | "3.403"
request |  
route | "/swlist"

status | "ok"
-- | --
version | "3.403"
request |  
route | "/swlist"
response |  
0 |  
id | 0
name | "Somfy voorkant"
type | "somfy"
mode | 0
favorite | "no"
1 |  
id | 1
name | "Lamp dressoir"
type | "switch"
status | "off"
favorite | "no"
2 |  
id | 2
name | "Lamp raam"
type | "switch"
status | "off"
favorite | "no"
3 |  
id | 3
name | "Reserve"
type | "switch"
status | "off"
favorite | "no"

using:
domoticz version:  3.9629
Phyton version:    3.5.3
OS :                     Rasbian
Hardware:            Raspberry 2b

**Comment by rvdvoorde** [comment]
This should be solved if you use the latest domoticz beta
