### ISSUE TITLE
No updates 

### ISSUE THREAD

**Issue by St0kje** [rvdvoorde/domoticz-homewizard#29]
When I add a new contactsensor to my HW, the update doesn't appear in Domoticz. 

How do I update??

KR Andre

**Comment by rvdvoorde** [comment]
Hi Andre,

Did you restart Domoticz or updated the Homewizard hardware in Domoticz? 

Gr.
Raymond

**Comment by St0kje** [comment]
Thanks for the quick reply. I did both. i didn’t feel much to remove the homeward in domoticz. Then I would lose all the history. 

I now removed de doorcontact and renamed the contact in HW. Now it appear in Domoticz. Seems like it’s solved this way


Met vriendelijke groet,

Andre Hartman


⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯
⋮				         http://www.andrehartmanfotografie.nl					   ⋮
⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯⋯
