### ISSUE TITLE
Error on reading Energy meter values

### ISSUE THREAD

**Issue by Haringstad** [rvdvoorde/domoticz-homewizard#3]
I only keep getting the following error:

Error: (HomeWizard) Error on setting the Wattcher values!

It did detect my gas and electricity meter properly, but.....

Here is output of my /get-sensors:

        "energylinks": [
            {
                "aggregate": {
                    "dayTotal": 8.29, 
                    "po": 569, 
                    "po+": 2554, 
                    "po+t": "15:58", 
                    "po-": 215, 
                    "po-t": "12:44"
                }, 
                "c1": 0, 
                "c2": 0, 
                "code": "541989", 
                "favorite": "no", 
                "gas": {
                    "dayTotal": 0.73, 
                    "lastHour": 0.0
                },                 "id": 0, 
                "kwhindex": 0.0, 
                "name": "EnergyLink", 
                "s1": null, 
                "s2": null, 
                "t1": "none", 
                "t2": "none", 
                "tariff": 1, 
                "used": {
                    "dayTotal": 8.28, 
                    "po": 569, 
                    "po+": 2554, 
                    "po+t": "15:58", 
                    "po-": 215, 
                    "po-t": "12:44"
                }, 
                "wp": 0
            }            }
        ], 
        "energymeters": [],

**Comment by rvdvoorde** [comment]
With this latest fix at least the warning "Error on setting the Wattcher values!" should be gone. I still need more time for the energylinks and since I don't own one it's not easy...

**Comment by ghost** [comment]
I have an Energylink, happy to test

**Comment by rvdvoorde** [comment]
@jvlagsma Does the current version create and update (full update poll interval) the electric and gas switches at all or not?
