### ISSUE TITLE
Heatlink not showing target temperature and manual temperature

### ISSUE THREAD

**Issue by azsystem** [rvdvoorde/domoticz-homewizard#30]
Not all values are published to domoticz.

tte = target temperature when heatlink is in control (id:131)
rsp = target temperature when thermostat is in control (id: 130)
         in case the thermostat is in control, the tte value is set to 0.
wp = waterpressure in bar (not implemented in code)

Please include these values, so they can be used in domoticz.

**Comment by azsystem** [comment]
Add id 130, 131. 
Change int to round to display decimals in temperature

[plugin.zip](https://github.com/rvdvoorde/domoticz-homewizard/files/3000288/plugin.zip)

Waterpressure not yet implemented

**Comment by rvdvoorde** [comment]
Merged your changes
