### ISSUE TITLE
Hue and Smartwares lights

### ISSUE THREAD

**Issue by erwinbierens** [rvdvoorde/domoticz-homewizard#34]
Hi,

first of all thanks for this great plugin! 
I've noticed i'm missing some light showing up in Domoticz. 

**http://ip//password/swlist is showing these:**
    _{"id":12,"name":"Dressoir Rechts","type":"hue","status":"off","hue_id":0,"light_id":3,"color":{"hue":109,"sat":8,"bri":51},"favorite":"no"},
    {"id":13,"name":"Dressoir links","type":"hue","status":"off","hue_id":0,"light_id":1,"color":{"hue":60,"sat":0,"bri":44},"favorite":"no"},
    {"id":14,"name":"Lamp bank","type":"hue","status":"off","hue_id":0,"light_id":2,"color":{"hue":45,"sat":1,"bri":36},"favorite":"no"},
    {"id":16,"name":"zolder 1","type":"led5ch","status":"off","color":{"hue":100,"sat":0,"bri":60},"version":5.04,"favorite":"no"},
    {"id":17,"name":"zolder 2","type":"led5ch","status":"off","color":{"hue":100,"sat":0,"bri":60},"version":5.04,"favorite":"no"},
    {"id":18,"name":"zolder boven ","type":"led5ch","status":"off","color":{"hue":100,"sat":0,"bri":60},"version":5.04,"favorite":"no"}]}_

12/13/14 are from the HUE bridge. 
16/17/18 are Smartwares Connected Led HW1601 lights (https://www.homewizard.nl/shop/smartwares-connected-e27-kleuren-led-lamp-hw1601) 

is it possible to add these types (hue and led5ch) in to the script?

**Comment by rvdvoorde** [comment]
Hi Erwin,

Why use Homewizard to connect the Philips HUE lights to Domoticz? Domoticz has integrated the Philips HUE bridge and that is why I didn't add this to this plugin.

**Comment by erwinbierens** [comment]
Hi Raymond,

I know, but for migrations this is a good way to convert everything to domoticz.

What about the smartwares lights?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
