### ISSUE TITLE
Installed on Raspberry Pi, but do not see the plugin

### ISSUE THREAD

**Issue by corvankruchten** [rvdvoorde/domoticz-homewizard#39]
I installed the plug-in as described, even tried some updates. But I cannot see the homeward in my Domoticz. I checked the directory with plugins: it is there. I rebooted several times without result...

**Comment by c4coer** [comment]
hello 
what folder do you copy the plugin.py
for example on synology and docker the folder is \domoticz\plugins\hw\plugin.py

**Comment by corvankruchten** [comment]
domoticz/plugins/domoticz-homewizard/

**Comment by c4coer** [comment]
may be rename the folder 
domoticz/plugins/hw/

**Comment by corvankruchten** [comment]
Unfortunately it didn’t do the trick..

**Comment by corvankruchten** [comment]
I think I found it: I reinstalled Python ( sudo apt install python3-dev) and restarted Domoticz. One of these two did the job.
