### ISSUE TITLE
Somfy screen close opens screen

### ISSUE THREAD

**Issue by caspelr** [rvdvoorde/domoticz-homewizard#42]
Both the open and the close action on domoticsz opens the screen.
previous domoticz used on and off i think but now open and close.
changed line 297  to             if ( (str(Command).lower() == "on") or (str(Command).lower() == "open") ):
and reversed the actions.
Is anyone, beside me, still using this plugin????

**Comment by rvdvoorde** [comment]
Thanks for your change. I only use it because the homewizard is not broken yet ;-) So I read a few temp sensors with it.
