### ISSUE TITLE
Plugin not loading anymore

### ISSUE THREAD

**Issue by sabiwa** [rvdvoorde/domoticz-homewizard#6]
Since a recent update to the Domoticz beta the plugin isn't loaded anymore.

Has anything changed ?

**Comment by nepheris** [comment]
I have the same problem. 
I tryed to uninstall and delete the folder to install it again but it did not fix it ! 

Can you please help me with a correction of the code or a procedure to uninstall an re-installl in a proper way ? 
Thanks for your help.

**Comment by sabiwa** [comment]
I did now build domoticz on my raspberry manually with the python enabled brance and it worked

**Comment by nepheris** [comment]
Problem solved with last update Thanks

**Comment by sabiwa** [comment]
Check works with me also on pre-build version again
